import 'package:flutter/cupertino.dart';
import 'package:get/get.dart';

class LocalizationService extends Translations {
  static getLocalizedKey(String key) {
    String currentLanguageCode = Get.locale!.languageCode;
    debugPrint('Localized key is: ${key}_$currentLanguageCode');
    return '${key}_$currentLanguageCode';
  }

  @override
  Map<String, Map<String, String>> get keys {
    // ignore: constant_identifier_names
    const Map<String, String> lang_en = {
      "hello": "Hello world!",
      "order_placed": "Order Placed",
      "order_accepted": "Order Accepted",
      "complete": "Complete Profile",
      "order_processed": "Order Processed",
      "order_ready": "Order Ready to Pick",
      "order_completed": "Order Completed",
      "drafts": "Drafts",
      "place_ord": "Place Order",
      "published": "Published",
      "protection": "Buyer Protection",
      "protection_include": "Including Buyer protection",
      "sales": "Selling",
      "incl": "incl.",
      "add_to_cart": "Add to cart",
      "published_items": "Published",
      "pending_pickup": "Pending buyer pickup",
      "buying": "Buying",
      "wishlist": "Wish List",
      "shopping_cart": "Shopping Cart",
      "to_pick": "To pickup",
      "sure_delete_item":
          "Are you sure that want to delete the item and its pictures? This cannot be undone.",
      "yes": "Yes",
      "no": "No",
      "are_you_sure": "Are you sure",
      "ok": "OK",
      "cancel": "Cancel",
      "title": "Title",
      "description": "Description",
      "color": "Color",
      "material": "Material",
      "size": "Size",
      "weight": "Weight",
      "items_hidden": "Your items are hidden",
      "holday_on": "Holiday is now on",
      "condition": "Condition",
      "recommended-price": "Recommended Price",
      "style": "Style",
      "publish": "Publish",
      "delete": "Delete",
      "edit": "Edit",
      "language": "Language",
      "developer-settings": "Developer Settings",
      "my-addresses": "My Address",
      "edit-profile": "Edit Profile",
      "notifications": "Notifications",
      "new_request": "New Request",
      "settings": "Settings",
      "about-us": "About Us",
      "faqs": "FAQs",
      "contact-us": "Contact Us",
      "contact": "Contact",
      "logout": "Log Out",
      "want-to-logout": "Do you really want to log out?",
      "add-to-wishlist":
          "Tap the heart icon on items in the store to add items to your wishlist.",
      "unpublish": "Unpublish",
      "location_access_details":
          "To view nearby products, provide your zip code or allow your location:",
      "location_access": "Location Access",
      "location_disable": "Location services are disabled",
      "location_permision_den": "Location permissions are denied.",
      "location_permision_den_permanent":
          "Location permissions are permanently denied, we cannot request permissions.",
      "allow": "ALLOW",
      "do_you_really_want_to_close_the_application":
          "Do you really want to close the application?",
      "buy": "Buy",
      "sell": "Sell",
      "sell_an_item": "Sell an Item",
      "product_saved_successfully": "Product saved successfully!",
      "success": "Success!!",
      "error": "Error!",
      "unexpected_error": "An unexpected error occurred, try again later",
      "item_price_should_be_added": "Item price should be added!",
      "product_updated_successfully": "Product updated successfully!",
      "product_unpublished_successfully": "Product unpublished successfully!",
      "product_deleted_successfully": "Product deleted successfully!",
      "pickup": "Pickup",
      "failed": "Failed to load!",
      "verify_email": "verify your email or phone number",
      "complete_profile": "Profile not completed",
      "profile_not_com": "",
      "take_picture": "Take Picture",
      "do_you_really_want_to_delete_this_image":
          "Do you really want to delete this image?",
      "done": "Done",
      "order": "Order#",
      "status": "Status: ",
      "track_order": "Track Order",
      "new_address_added": "New address successfuly added!",
      "new_address_updated": "Address successfuly updated!",
      "add_address": "Add Address",
      "selling_address": "Selling Address",
      "to_be_able_to_publish":
          "To be able to publish, you need to supply your address",
      "address_line_1": "Address Line 1",
      "required_field": "Required field",
      "address_line_2": "Address Line 2",
      "edit_address": "Edit Address",
      "edit_product": "Edit product",
      "update_product": "Update Product",
      "save_address": "Save Address",
      "addresses": "Address",
      "address_not_found": "Address not found",
      "add_new_address": "Add New Address",
      "address": "Address",
      "do_you_really_want_to_delete_this_address":
          "Do you really want to delete this address?",
      "address_selected_as_default": "Address selected as default",
      "welcome_to": "Welcome to",
      "please_login_with_your": "Please login with your:",
      "order_is_not_been_accepted": "Order is not been accepted",
      "alert": "Alert!",
      "choose_your_address": "Choose your address",
      "default_address": "Default Address: ",
      "pay_now": "Pay Now",
      "payment_met": "Payment Method",
      "ordered_items": "Ordered Items",
      "seller_details": "Seller Details: ",
      "name": "Name",
      "phone": "Phone",
      "completed": "Completed",
      "order_completed_on": "Order completed on ",
      "you_need_to_mark_complete_after_pickup":
          "Du måste markera komplett efter upphämtning",
      "payment_will_be_released_to_seller":
          "Payment will be released to seller",
      "mark": "Mark",
      "enter_card_details": "Please enter your bank card details",
      "payment_cancelled": "Payment cancelled, please try again",
      "select_payment": "Please select a payment method",
      "payment_unsuccessful": "Payment unsuccessful, please try again",
      "order_placed_successfully": "Your order has been successfully placed",
      "chats": "Chats",
      "search": "Search",
      "write_message": "Write Message",
      "price": "Price",
      "model": "Model",
      "and": "And",
      "brand": "Brand",
      "payment": "Payment",
      "you_will_now_see_products_near_you":
          "You will now see products near you",
      "search_products": "Search products...",
      "filter_by_categories": "Filter by Categories",
      "categories": "Categories",
      "categories_not_found": "Categories Not Found!",
      "clear": "Clear",
      "sub_categories": "Sub Categories:",
      "apply": "Apply",
      "edit_profile": "Edit Profile",
      "first_name": "First Name",
      "last_name": "Last Name",
      "phone_no": "Phone no",
      "update": "Update",
      "enter_valid_email": "Please Enter a Valid Email",
      "enter_valid_phone": "Please Enter a Valid Phone No",
      "profile_successfully_updated": "Profile successfully updated",
      "select_language": "Select Language ",
      "select_locker": "Select Locker ",
      "languages": "Languages",
      "automatic": "Automatic",
      "swedish": "Swedish",
      "english": "English",
      "do_you_really_want_to_delete_this_notification":
          "Do you really want to delete this notification?",
      "notification_delete_successfully": "Notification delete successfully",
      "bankid_login": "BankID Login",
      "change": "Change",
      "you_are_logged_out": "You are logged out.",
      "category_required": "Category Required!",
      "please_select_category_and_sub_category_for_the_item":
          "Please select category and sub category for the item",
      "buyer_details": "Buyer Details",
      "details": "Details",
      "marked_as_accepted": "Marked as accepted",
      "buyer_will_be_notified":
          "Buyer will be notified for the order preparation.",
      "buyer_will_pick_the_order":
          "Buyer will pick the order from given location.",
      "you_need_to_mark_for_pickup": "You need to mark complete after pickup",
      "favorites": "Favorites",
      "summary": "Summary",
      "netpay": "Net Pay",
      "saltax": "Sales Tax",
      "commession": "Plateform Commission",
      "you_cant_buy_your_product": "You can not buy your own products",
      "cart": "Cart",

      /// New App Keys

      "your_searches": "Your Searches",
      "items": "Items",
      "members": "Members",
      "members_item": "Member Items",
      "similar_item": "Similar Items",
      "no_items_added": "No other item added by this member yet!",
      "next": "Suivant",
      "reviews": "Reviews",
      "reviews_not_added": "Review not added yet!",
      "start_now": "Start Now!",
      "onboarding_title1": "Achetez et vendez facilement",
      "onboarding_title2": "Gagnez de l'argent depuis chez vous",
      "onboarding_title3": "Livraison rapide et sécurisée",
      "onboarding_title4": "Paiement à la livraison",
      "onboarding_des1":
          "Rejoignez la communauté Chedmed pour acheter et vendre des produits en toute sécurité",
      "onboarding_des2":
          " Vendez vos produits inutilisés et gagnez de l'argent rapidement et facilement",
      "onboarding_des3":
          "Vendez vos produits inutilisés et gagnez de l'argent rapidement et facilement",
      "onboarding_des4":
          "Achetez et vendez en toute sécurité dans toutes les villes du Maroc",
      "welcom_text":
          "Become part of the second-hand trend and enjoy free selling!",
      "login": "Login",
      "login_required_description":
          "It look like you are not Logged In, You need to login first...",
      "login_required": "Login Required!",
      "signup": "Sign Up",
      "continue_guest": "Continue as Guest?",

      "login_trext": "Login to your account",
      "cor_email_text": "Or use email address",
      "email": "Email",
      "email_validation": "Please Enter a Valid Email",
      "password": "Password",
      "password_dont_match": "Passwords do not match",
      "enter_password": "Please enter your password",
      "enter_password_again": "Please Enter Your New Password Again",
      "password_include_character": "Password must include 8 characters",
      "confirm_password": "Confirm Password",
      "forgot_password": "Forgot Password?",
      "new_member_text": "New Member?",
      "already_member": "Already a member?",
      "continue": "Continue",
      "new_account": "Create new account",
      "account": "Account",
      "agreement_text": "By signing up, you agree to our",
      "terms": "Terms of Service",
      "privacy": "Privacy Policy",
      "get_code": "Get Code",
      "verification": "Verification",
      "send_again": "Send Again",
      "send_offer": "Send Offer",
      "verify": "Verify",
      "verified": "Verified",
      "not_verified": "Not Verified",
      "email_verification": "Email Verification",
      "phone_verification": "Phone Verification",
      "input_field": "Input Field Required",
      "progress": "Still In Progress",
      "otp_sent_success": "Otp sent Successfully",
      "new_password": "New Password",
      "confirm_new_pass": "Confirm New Password",
      "update_pass": "Update Password",
      "registration": "Registration",
      "profile": "Profile",
      "about": "About",
      "gender": "Gender",
      "country": "Country",
      "state": "State",
      "city": "City",
      "street": "Street",
      "zip_code": "Zip Code",
      "bio": "Bio....",
      "submit": "Submit",
      "skip": "Skip",
      "undefined_error": "An undefined error occured, try again later.",
      "add": "ADD",
      "view_all": "View all",
      "guest_user": "Guest User",
      "good_morning": "Good Morning",
      "good_afternoon": "Good Afternoon",
      "good_evening": "Good Evening",
      "all_cat": "All Categories",
      "change_filter": "No products found for this filter, Change Your Filters",
      "category": "Category",

      "save": "Save",
      "home": "Home",
      "products": "Products",
      "filter": "Filter",
      "products_not_found": "Products not found!",
      "make_offer": "Make an Offer",
      "buy_now": "Buy Now",
      "interest": "Interests",
      "view_by": "Viewed By",
      "uploaded": "Uploaded",
      "upload": "Upload",
      "uploaded_photo": "Upload Photo",
      "take_photo": "Take Photo",
      "uploaded_photo_text": "Upload up to 15 Photos.",
      "list_by": "Listed By",
      "ask_seller": "Ask Seller",
      "natural_light": "Natural Lights",
      "year": "Year",
      "ago": "ago",
      "month": "month",
      "day": "day",
      "today": "Today",
      "pruduct_search": "Please search products!",
      "close": "Close",
      "sort_by": "Sort by",
      "price_rage": "Price Range",
      "lo_to_hi": "Low to High",
      "hi_to_lo": "High to Low",
      "newest_first": "Newest First",
      "from": "From",
      "to": "To",
      "see_tips": "See Photos tips",
      "parcel_size": "Parcel Size",
      "photo_tips": "Photo Tips",
      "color_selection": "You can select only two Colors",
      "chose_natural_light": "Choose Natural Lights",
      "pick_neutral_background": "Pick a Neutral Background",
      "dont_flash": "Don’t Use Flash",
      "show_items": "Show Off Your Items",
      "own_images": "Use Your own Images",
      "product_uploaded": "Product Uploaded!",
      "product_upload_message":
          "Products successfuly added, please wait for the approval",

      /// Profile
      "my_profile": "My Profile",
      // "edit_profile": "My Profile",
      "my_ads": "My Ads",
      "spotlight_charges": "Spotlight Charges:",
      "bump_item": "Bump Your Items",
      "store_spotlight": "Spotlight Your Store",
      "boos_visib": "Boost Your Visibility",
      "my_listing": "My Listings",
      "my_order": "My Orders",
      "my_wallet": "My Wallet",
      "my_address": "My Addresses",
      "fav_items": "Favorite Items",
      "hide_items": "Hide my items",
      "personalisation": "Personalisation",
      "account_settings": "Account Setting",
      "other_setting": "Other Settings",
      "others": "Others",
      "impressions": "Impressions",
      "no_products": "No Products Listed Yet",
      "sold": "Sold",
      "bought": "Bought",
      "no_pen_orders": "No Order is Pending",
      "no_proc_order": "No Order in Proccessing",
      "no_com_order": "No Order is Completed",
      "no_can_order": "No Order is Cancelled",
      "no_ord_placed": "No Order Placed Yet",
      "all": "All",
      "pending": "Pending",
      "processing": "Processing",
      "offer_message":
          "Your offer must be at least 40% off of the original price",
      "cancelled": "Cancelled",
      "history": "History",
      "no_trans": "You have do not have any Transaction",
      "balance": "Available Balance",
      "withdraw": "WithDraw",
      "bank_account_seleted": "Bank Account must be Selected",
      "withdraw_text":
          "It may take up to 5 business days for the funds to reach your bank account.",
      "upcomming_bal": "Upcoming Balance",
      "no_fav": "No Products in the Whish List",
      "personalize_feed":
          "Choose your preferred categories and sizes to personalize your feed",
      "following": "Following",
      "aply_person": "Personalization Applied successfully",
      "account_sett": "Account Setting",
      "not_sel": "Not Selected",
      "not_spec": "Not Specified",
      "on": "On",
      "off": "Off",
      "holy_day": "Holiday Mode",
      "dob": "Date of Birth",
      "enter_dob": "Enter DoB",
      "acc_sync": "Accounts & Sync",
      "email_phone_ver": "Email & Phone Verification",
      "delete_acc": "Delete Account",
      "delete_account_text": "Do you really want to Delete your Account",
      "chagne_pass": "Change Password",
      "chagne_pass_text": "Password Changed sucessfully",
      "current_pass": "Current Passwod",
      "enter_current_pass": "Please enter your Current password",
      "dark_mode": "Dark Mode",
      "bundle_discount": "Bundle Discount",
      "enable_bundel_dis": "Enable Bundle Discount",
      "setup_dis": "Setup discount",
      "bundle_discount_success": "Bundle Discount Created Successfully",
      "two_factor": "2 factor Authentication (2FA)",
      "terms_and_con": "Terms & Condition",
      "return_policy": "Return & Refund Policy",
      "customer_support": "Customer Support",
      "no_support_req": "No Support Requests Found!",
      "invalid_pass": "Invalid Password",
      "disconut_selection_text": "Discount Percentage must be selected",
      "user_blocked": "This User has been Blocked",
      "user_reported": "The User has been Reported",
      "report_user_text": "Are you sure you want to report this account?",
      "report": "Report",
      "report_user": "Report User",
      "or": "Or",
      "delivery_address": "Delivery Address",
      "delivery_company": "Delivery Companies",
      "shipping_service_not_av": "Shipping Service not availible",
      "shipping_service_selected": "Shipping Service must be Selected",
      "save_filter": "Filter Saved Successfully",
      "withdraw_request_succes":
          "Your Withdrawl Request has been sent Successfully",
      "withdraw_request": "Withdraw Request",
      "amount": "Amount",
      "no_bank_account": "No Bank Accounts Added Yet",
      "add_new": "Add New Account",
      "review_success": "Review added Successfully",
      "location_entered": "Location must be entered",
      "conversation_blocked": "You have Blocked ",
      "user_blocked_you": "You have been Blocked by ",
      "accept": "Accept",
      "reject": "Reject",
      "help_center": "Help Center",
      "checkout": "Checkout",
      "withDraw": "WithDraw",
      "say_somthing": "Say Something",
      "rating": "Rating",
      "no_comment": "No comments",
      "proceed": "Proceed",
      "proceed_checkout": "Proceed to Checkout",
      "review": "Review",
      "gallery": "Gallery",
      "pick_image": "Pick Image",
      "member_since": "Member Since",
      "block": "Block",
      "block_user_text": "Are you sure you want to block this user?",
      "block_user": "Block User",
      "delete_convesation": "Delete Conversation",
      "delete_conversation_text":
          "Are you sure you want to delete this conversation?",
      "delete_chat": "Delete Chat",
      "order_detail": "Order Details",
      "order_id": "Order ID",
      "last_update": "Last Update:",
      "shipping_addr": "Shipping Address:",
      "subtotal": "Sub total",
      "minuts": "Mins",
      "finances": "FINANCES",
      "order_supp": "COMMANDE",
      "prod_supp": "PRODUCT",
      "withdraw_supp": "WITHDRAW",
      "deposite": "DEPOSIT",
      "enter_message": "Please enter a message",
      "enter_title": "Please enter a title",
      "select_type": "Select Type",
      "new_req": "New Request",
      "total": "Total",
      "ord_samm": "Order Sammary",
      "view_states": "View States",
      "statistics": "Statistics",
      "clicks": "Clicks",
      "delivery_charges": "Delivery charges",
      "connected": "Connected",
      "not_connected": "Not Connected",
      "set_price": "Set a price",
      "custom": "Custom",
      "views": "views",
      "want_holiday_mode": "Do you want to turn on Holiday Mode?",
      "user": "User",
      "guide_step1_message":
          "Choose your preferred language to continue: French, English, or Darija.",
      "guide_step2_message":
          "Use the navigation bar to explore categories, manage your profile, and access settings.",
      "guide_step3_message":
          "Click on 'Sell Item' to list your products. Add photos, descriptions, and set your price!",
      "guide_step4_message":
          "Use the search bar to find items you love. Apply filters to refine your search.",
      "guide_step5_message":
          "Found something you like? Propose a price and negotiate directly with the seller!",
      "guide_step6_message":
          "Access your profile to edit it and confirm your phone number. This builds trust with other users.",
      "guide_step7_message":
          "Going on vacation? Activate vacation mode in settings to temporarily hide your items.",
      "guide_step8_message":
          "Group multiple items from the same seller to create a bundle and save on shipping costs. Click 'Create Bundle' to get started!",
      "guide_step9_message":
          "You’re ready to explore شَدْ مَدْ! Start buying, selling, and exchanging items today.",

      "try_now": "Try Now",
      "got_it": "Got it!",
      "create_bundle": "Create Bundle",
      "start_exploring": "Start Exploring",
      'show_more': 'Show More',
      'show_less': 'Show Less'
    };

    // ignore: constant_identifier_names
    const Map<String, String> lang_ar = {
      "order_placed": "تم تقديم الطلب",
      "order_accepted": "تم قبول الطلب",
      "complete": "مكتمل",
      "order_processed": "تمت معالجة الطلب",
      "order_ready": "الطلب جاهز للاستلام",
      "order_completed": "اكتمل الطلب",
      "drafts": "المسودات",
      "place_ord": "وضع النظام",
      "published": "منشور",
      "protection": "حماية المشتري",
      "protection_include": "بما في ذلك حماية المشتري",
      "sales": "المبيعات",
      "incl": "شامل",
      "add_to_cart": "أضف إلى السلة",
      "published_items": "العناصر المنشورة",
      "pending_pickup": "في انتظار الاستلام",
      "buying": "الشراء",
      "wishlist": "قائمة الرغبات",
      "shopping_cart": "عربة التسوق",
      "to_pick": "للاستلام",
      "sure_delete_item":
          "هل أنت متأكد من أنك تريد حذف العنصر وصوره؟ لا يمكن التراجع عن هذا.",
      "yes": "نعم",
      "no": "لا",
      "are_you_sure": "هل أنت متأكد؟",
      "ok": "موافق",
      "cancel": "إلغاء",
      "title": "العنوان",
      "description": "الوصف",
      "color": "اللون",
      "material": "المادة",
      "size": "الحجم",
      "weight": "الوزن",
      "items_hidden": "العناصر الخاصة بك مخفية",
      "holday_on": "لقد بدأت العطلة الآن",
      "condition": "الحالة",
      "recommended-price": "السعر الموصى به",
      "style": "النمط",
      "publish": "نشر",
      "delete": "حذف",
      "edit": "تعديل",
      "language": "اللغة",
      "developer-settings": "إعدادات المطور",
      "my-addresses": "عناويني",
      "edit-profile": "تعديل الملف الشخصي",
      "notifications": "الإشعارات",
      "new_request": "طلب جديد",
      "settings": "الإعدادات",
      "about-us": "معلومات عنا",
      "faqs": "الأسئلة الشائعة",
      "contact-us": "اتصل بنا",
      "contact": "اتصال",
      "logout": "تسجيل الخروج",
      "want-to-logout": "هل تريد بالفعل تسجيل الخروج؟",
      "add-to-wishlist":
          "اضغط على أيقونة القلب على العناصر في المتجر لإضافتها إلى قائمة الرغبات الخاصة بك.",
      "unpublish": "إلغاء النشر",
      "location_access_details":
          "لعرض المنتجات القريبة، يرجى توفير الرمز البريدي أو السماح بالوصول إلى موقعك:",
      "location_access": "الوصول إلى الموقع",
      "location_disable": "تم تعطيل خدمات الموقع",
      "location_permision_den": "تم رفض أذونات الموقع.",
      "location_permision_den_permanent":
          "تم رفض أذونات الموقع بشكل دائم، لا يمكننا طلب الأذونات.",
      "allow": "السماح",
      "do_you_really_want_to_close_the_application":
          "هل تريد حقًا إغلاق التطبيق؟",
      "buy": "شراء",
      "sell": "بيع",
      "sell_an_item": "بيع عنصر",
      "product_saved_successfully": "تم حفظ المنتج بنجاح!",
      "success": "نجاح!!",
      "error": "خطأ!",
      "unexpected_error": "حدث خطأ غير متوقع، يرجى المحاولة لاحقًا.",
      "item_price_should_be_added": "يجب إضافة سعر العنصر!",
      "product_updated_successfully": "تم تحديث المنتج بنجاح!",
      "product_unpublished_successfully": "تم إلغاء نشر المنتج بنجاح!",
      "product_deleted_successfully": "تم حذف المنتج بنجاح!",
      "pickup": "الاستلام",
      "failed": "فشل التحميل!",
      "verify_email": "التحقق من بريدك الإلكتروني أو رقم هاتفك",
      "complete_profile": "الملف الشخصي لم يكتمل",
      "profile_not_com": "يرجى استكمال الملف الشخصي الخاص بك",
      "take_picture": "التقط صورة",
      "do_you_really_want_to_delete_this_image": "هل تريد حقًا حذف هذه الصورة؟",
      "done": "تم",
      "order": "طلب#",
      "status": "الحالة: ",
      "track_order": "تتبع الطلب",
      "new_address_added": "تمت إضافة العنوان الجديد بنجاح!",
      "new_address_updated": "تم تحديث العنوان بنجاح!",
      "add_address": "إضافة عنوان",
      "selling_address": "عنوان البيع",
      "to_be_able_to_publish": "لنشر المنتج، يجب عليك تقديم عنوانك",
      "address_line_1": "السطر الأول من العنوان",
      "required_field": "حقل مطلوب",
      "address_line_2": "السطر الثاني من العنوان",
      "edit_address": "تعديل العنوان",
      "edit_product": "تحرير المنتج",
      "update_product": "تحديث المنتج",
      "save_address": "حفظ العنوان",
      "addresses": "العناوين",
      "address_not_found": "لم يتم العثور على العنوان",
      "add_new_address": "إضافة عنوان جديد",
      "address": "العنوان",
      "do_you_really_want_to_delete_this_address":
          "هل تريد حقًا حذف هذا العنوان؟",
      "address_selected_as_default": "تم تحديد العنوان كافتراضي",
      "welcome_to": "مرحبًا بك في",
      "please_login_with_your": "يرجى تسجيل الدخول باستخدام:",
      "order_is_not_been_accepted": "لم يتم قبول الطلب",
      "alert": "تنبيه!",
      "choose_your_address": "الرجاء إدخال عنوانك للمضي قدما",
      "default_address": "العنوان الافتراضي: ",
      "pay_now": "ادفع الآن",
      "payment_met": "طريقة الدفع",
      "ordered_items": "العناصر المطلوبة",
      "seller_details": "تفاصيل البائع: ",
      "name": "الاسم",
      "phone": "الهاتف",
      "completed": "مكتمل",
      "order_completed_on": "تم اكتمال الطلب في ",
      "you_need_to_mark_complete_after_pickup":
          "يجب عليك تحديد الطلب كمكتمل بعد الاستلام",
      "payment_will_be_released_to_seller": "سيتم تحويل الدفع إلى البائع",
      "mark": "تحديد",
      "enter_card_details": "الرجاء إدخال تفاصيل بطاقتك المصرفية",
      "payment_cancelled": "تم إلغاء الدفع، يرجى المحاولة مرة أخرى",
      "select_payment": "يرجى اختيار طريقة الدفع",
      "payment_unsuccessful": "فشل الدفع، يرجى المحاولة مرة أخرى",
      "order_placed_successfully": "تم تقديم طلبك بنجاح",
      "chats": "الدردشات",
      "search": "بحث",
      "write_message": "اكتب رسالة",
      "price": "السعر",
      "model": "الموديل",
      "and": "و",
      "brand": "العلامة التجارية",
      "payment": "قسط",
      "you_will_now_see_products_near_you": "سترى الآن المنتجات القريبة منك",
      "search_products": "ابحث عن المنتجات...",
      "filter_by_categories": "تصفية حسب الفئات",
      "categories": "الفئات",
      "categories_not_found": "الفئات غير موجودة!",
      "clear": "مسح",
      "sub_categories": "الفئات الفرعية:",
      "apply": "تطبيق",
      "edit_profile": "تعديل الملف الشخصي",
      "first_name": "الاسم الأول",
      "last_name": "الاسم الأخير",
      "phone_no": "رقم الهاتف",
      "update": "تحديث",
      "enter_valid_email": "الرجاء إدخال بريد إلكتروني صحيح",
      "enter_valid_phone": "الرجاء إدخال رقم هاتف صحيح",
      "profile_successfully_updated": "تم تحديث الملف الشخصي بنجاح",
      "select_language": "اختر اللغة",
      "select_locker": "حدد الخزانة",
      "languages": "اللغات",
      "automatic": "تلقائي",
      "swedish": "السويدية",
      "english": "الإنجليزية",
      "do_you_really_want_to_delete_this_notification":
          "هل تريد حقًا حذف هذا الإشعار؟",
      "notification_delete_successfully": "تم حذف الإشعار بنجاح",
      "bankid_login": "تسجيل الدخول باستخدام BankID",
      "change": "تغيير",
      "you_are_logged_out": "لقد تم تسجيل خروجك.",
      "category_required": "الفئة مطلوبة!",
      "please_select_category_and_sub_category_for_the_item":
          "الرجاء تحديد الفئة والفئة الفرعية للعنصر",
      "buyer_details": "تفاصيل المشتري",
      "details": "تفاصيل",
      "marked_as_accepted": "تم وضع علامة كمقبول",
      "buyer_will_be_notified": "سيتم إعلام المشتري بتحضير الطلب.",
      "buyer_will_pick_the_order":
          "سيقوم المشتري باختيار الطلب من الموقع المحدد.",
      "favorites": "المفضلات",
      "summary": "ملخص",
      "netpay": "صافي الدفع",
      "saltax": "ضريبة المبيعات",
      "commession": "لجنة المنصة",
      "you_cant_buy_your_product": "لا يمكنك شراء منتجاتك الخاصة",
      "cart": "العربة",
      "your_searches": "بحثك",
      "items": "العناصر",
      "members": "الأعضاء",
      "members_item": "عناصر الأعضاء",
      "similar_item": "عناصر مشابهة",
      "no_items_added": "لم يتم إضافة عناصر أخرى من قبل هذا العضو بعد!",
      "next": "التالي",
      "reviews": "التعليقات",
      "reviews_not_added": "لم تتم إضافة التعليق بعد!",
      "start_now": "ابدأ الآن!",
      "onboarding_title1": "اشتري وبيع بسهولة",
      "onboarding_title2": "اكسب المال من المنزل",
      "onboarding_title3": "توصيل سريع وأمنً",
      "onboarding_title4": "الدفع عند الاستلامً",
      "onboarding_des1": "انضم إلى مجتمع شَدْمَدْ لشراء وبيع المنتجات بأمان",
      "onboarding_des2": "بِعْ منتجاتك غير المستخدمة واكسب المال بسرعة وسهولة",
      "onboarding_des3":
          "استمتع بتوصيل سريع وأمن مع أفضل شركائنا، الدفع عند الاستلام متاح",
      "onboarding_des4": "اشتري وبِعْ بكل أمان في جميع مدن المغرب",
      "welcom_text":
          "كن جزءاً من اتجاه المنتجات المستعملة واستمتع بالبيع المجاني!",
      "login": "تسجيل الدخول",
      "login_required_description":
          "يبدو أنك غير مسجل، يجب عليك تسجيل الدخول أولاً...",
      "login_required": "تسجيل الدخول مطلوب!",
      "signup": "التسجيل",
      "continue_guest": "مواصلة كزائر؟",
      "login_trext": "تسجيل الدخول إلى حسابك",
      "cor_email_text": "أو استخدم عنوان البريد الإلكتروني",
      "email": "البريد الإلكتروني",
      "email_validation": "يرجى إدخال بريد إلكتروني صالح",
      "password": "كلمة المرور",
      "password_dont_match": "كلمات المرور غير متطابقة",
      "enter_password": "يرجى إدخال كلمة المرور",
      "enter_password_again": "يرجى إدخال كلمة المرور الجديدة مرة أخرى",
      "password_include_character": "يجب أن تتضمن كلمة المرور 8 أحرف",
      "confirm_password": "تأكيد كلمة المرور",
      "forgot_password": "هل نسيت كلمة المرور؟",
      "new_member_text": "عضو جديد؟",
      "already_member": "هل أنت عضو بالفعل؟",
      "continue": "مواصلة",
      "new_account": "إنشاء حساب جديد",
      "account": "الحساب",
      "agreement_text": "من خلال التسجيل، أنت توافق على",
      "terms": "شروط الخدمة",
      "privacy": "سياسة الخصوصية",
      "get_code": "الحصول على الرمز",
      "verification": "التحقق",
      "send_again": "إرسال مرة أخرى",
      "send_offer": "إرسال العرض",
      "verify": "تحقق",
      "verified": "تم التحقق منها",
      "not_verified": "لم يتم التحقق منها",
      "email_verification": "التحقق من البريد الإلكتروني",
      "phone_verification": "التحقق من الهاتف",
      "input_field": "حقل الإدخال مطلوب",
      "progress": "لا يزال قيد المعالجة",
      "otp_sent_success": "تم إرسال الرمز بنجاح",
      "new_password": "كلمة المرور الجديدة",
      "confirm_new_pass": "تأكيد كلمة المرور الجديدة",
      "update_pass": "تحديث كلمة المرور",
      "registration": "التسجيل",
      "profile": "الملف الشخصي",
      "about": "عن",
      "gender": "الجنس",
      "country": "البلد",
      "state": "الدولة",
      "city": "المدينة",
      "street": "الشارع",
      "bio": "السيرة الذاتية....",
      "submit": "إرسال",
      "skip": "تخطي",
      "undefined_error": "حدث خطأ غير معروف، حاول مرة أخرى لاحقاً.",
      "add": "إضافة",
      "view_all": "عرض الكل",
      "guest_user": "زائر",
      "good_morning": "صباح الخير",
      "good_afternoon": "مساء الخير",
      "good_evening": "مساء الخير",
      "all_cat": "جميع الفئات",
      "change_filter":
          "لم يتم العثور على منتجات لهذا الفلتر، قم بتغيير الفلاتر الخاصة بك",
      "category": "فئة",
      "save": "حفظ",
      "home": "الصفحة الرئيسية",
      "products": "المنتجات",
      "filter": "الفلتر",
      "products_not_found": "المنتجات غير موجودة!",
      "make_offer": "تقديم عرض",
      "buy_now": "اشتر الآن",
      "interest": "الاهتمامات",
      "view_by": "شاهد من قبل",
      "uploaded": "تم التحميل",
      "upload": "رفع",
      "uploaded_photo": "رفع صورة",
      "take_photo": "أخذ صورة",
      "uploaded_photo_text": "رفع حتى 15 صورة.",
      "list_by": "مدرج بواسطة",
      "ask_seller": "سؤال للبائع",
      "natural_light": "الضوء الطبيعي",
      "year": "سنة",
      "ago": "منذ",
      "month": "شهر",
      "day": "يوم",
      "today": "اليوم",
      "pruduct_search": "يرجى البحث عن المنتجات!",
      "close": "إغلاق",
      "sort_by": "فرز حسب",
      "price_rage": "نطاق السعر",
      "lo_to_hi": "من منخفض إلى مرتفع",
      "hi_to_lo": "من مرتفع إلى منخفض",
      "newest_first": "الأحدث أولاً",
      "from": "من",
      "to": "إلى",
      "see_tips": "شاهد نصائح الصور",
      "parcel_size": "حجم الطرد",
      "photo_tips": "نصائح التصوير",
      "color_selection": "يمكنك اختيار لونين فقط",
      "chose_natural_light": "اختر الضوء الطبيعي",
      "pick_neutral_background": "اختر خلفية محايدة",
      "dont_flash": "لا تستخدم الفلاش",
      "show_items": "عرض العناصر الخاصة بك",
      "own_images": "استخدم صورك الخاصة",
      "product_uploaded": "تم رفع المنتج!",
      "product_upload_message":
          "تم إضافة المنتجات بنجاح، يرجى الانتظار للموافقة",
      "my_profile": "ملفي الشخصي",
      "my_ads": "إعلاناتي",
      "spotlight_charges": "رسوم الأضواء:",
      "bump_item": "ادفع العناصر الخاصة بك",
      "store_spotlight": "تسليط الضوء على متجرك",
      "boos_visib": "تعزيز ظهورك",
      "my_listing": "قائمتي",
      "my_order": "طلباتي",
      "my_wallet": "محفظتي",
      "my_address": "عناويني",
      "fav_items": "العناصر المفضلة",
      "hide_items": "إخفاء العناصر الخاصة بي",
      "personalisation": "التخصيص",
      "account_settings": "إعدادات الحساب",
      "other_setting": "إعدادات أخرى",
      "others": "آحرون",
      "impressions": "انطباعات",
      "no_products": "لا توجد منتجات مدرجة بعد",
      "sold": "تم البيع",
      "bought": "تم الشراء",
      "no_pen_orders": "لا يوجد طلبات معلقة",
      "no_proc_order": "لا يوجد طلبات قيد المعالجة",
      "no_com_order": "لا يوجد طلبات مكتملة",
      "no_can_order": "لا يوجد طلبات ملغاة",
      "no_ord_placed": "لم يتم وضع أي طلب بعد",
      "all": "الكل",
      "pending": "معلق",
      "processing": "قيد المعالجة",
      "offer_message":
          "يجب أن يكون عرضك أقل من السعر الأصلي بنسبة 40% على الأقل",
      "cancelled": "ملغى",
      "history": "التاريخ",
      "no_trans": "لا توجد معاملات",
      "balance": "الرصيد المتاح",
      "withdraw": "السحب",
      "bank_account_seleted": "يجب اختيار حساب بنكي",
      "withdraw_text":
          "قد يستغرق الأمر ما يصل إلى 5 أيام عمل للوصول الأموال إلى حسابك البنكي.",
      "upcomming_bal": "الرصيد المقبل",
      "no_fav": "لا توجد منتجات في قائمة الرغبات",
      "personalize_feed": "اختر الفئات والأحجام المفضلة لديك لتخصيص تغذيتك",
      "following": "متابعة",
      "aply_person": "تم تطبيق التخصيص بنجاح",
      "account_sett": "إعدادات الحساب",
      "not_sel": "لم يتم الاختيار",
      "not_spec": "غير محدد",
      "on": "تشغيل",
      "off": "إيقاف",
      "holy_day": "وضع العطلة",
      "dob": "تاريخ الميلاد",
      "enter_dob": "أدخل تاريخ الميلاد",
      "acc_sync": "الحسابات والمزامنة",
      "email_phone_ver": "التحقق من البريد الإلكتروني والهاتف",
      "delete_acc": "حذف الحساب",
      "delete_account_text": "هل ترغب في حذف حسابك؟",
      "chagne_pass": "تغيير كلمة المرور",
      "chagne_pass_text": "تم تغيير كلمة المرور بنجاح",
      "current_pass": "كلمة المرور الحالية",
      "enter_current_pass": "يرجى إدخال كلمة المرور الحالية",
      "dark_mode": "الوضع المظلم",
      "bundle_discount": "خصم الحزمة",
      "enable_bundel_dis": "تمكين خصم الحزمة",
      "setup_dis": "إعداد الخصم",
      "bundle_discount_success": "تم إنشاء خصم الحزمة بنجاح",
      "two_factor": "التحقق بخطوتين (2FA)",
      "terms_and_con": "الشروط والأحكام",
      "return_policy": "سياسة الإرجاع والاسترداد",
      "customer_support": "دعم العملاء",
      "no_support_req": "لم يتم العثور على طلبات الدعم!",
      "invalid_pass": "كلمة مرور غير صالحة",
      "disconut_selection_text": "يجب تحديد نسبة الخصم",
      "user_blocked": "تم حظر هذا المستخدم",
      "user_reported": "تم الإبلاغ عن هذا المستخدم",
      "report_user_text": "هل أنت متأكد من أنك تريد الإبلاغ عن هذا الحساب؟",
      "report": "الإبلاغ",
      "report_user": "الإبلاغ عن المستخدم",
      "or": "أو",
      "delivery_address": "عنوان التوصيل",
      "delivery_company": "شركات التوصيل",
      "shipping_service_not_av": "خدمة الشحن غير متوفرة",
      "shipping_service_selected": "يجب اختيار خدمة شحن",
      "save_filter": "تم حفظ الفلتر بنجاح",
      "withdraw_request_succes": "تم إرسال طلب السحب بنجاح",
      "withdraw_request": "طلب السحب",
      "amount": "المبلغ",
      "no_bank_account": "لا توجد حسابات بنكية مضافة بعد",
      "add_new": "إضافة حساب جديد",
      "review_success": "تم إضافة التقييم بنجاح",
      "location_entered": "يجب إدخال الموقع",
      "conversation_blocked": "لقد قمت بحظر هذه المحادثة",
      "user_blocked_you": "لقد تم حظرك من قبل هذا المستخدم",
      "accept": "قبول",
      "reject": "رفض",
      "help_center": "مركز المساعدة",
      "checkout": "الدفع",
      "withDraw": "سحب",
      "say_somthing": "قل شيئا",
      "rating": "تصنيف",
      "no_comment": "لا تعليقات",
      "proceed": "يتابع",
      "proceed_checkout": "الشروع في الخروج",
      "review": "مراجعة",
      "gallery": "المعرض",
      "pick_image": "اختيار صورة",
      "member_since": "عضو منذ",
      "block": "حظر",
      "block_user_text": "هل أنت متأكد أنك تريد حظر هذا المستخدم؟",
      "block_user": "حظر المستخدم",
      "delete_convesation": "حذف المحادثة",
      "delete_conversation_text": "هل أنت متأكد أنك تريد حذف هذه المحادثة؟",
      "delete_chat": "حذف الدردشة",
      "order_detail": "تفاصيل الطلب",
      "order_id": "معرف الطلب",
      "last_update": "التحديث الأخير:",
      "shipping_addr": "عنوان الشحن:",
      "subtotal": "المجموع الفرعي",
      "minuts": "دقائق",
      "finances": "الشؤون المالية",
      "order_supp": "طلب",
      "prod_supp": "منتج",
      "withdraw_supp": "ينسحب",
      "deposite": "إيداع",
      "enter_message": "الرجاء إدخال رسالة",
      "enter_title": "الرجاء إدخال عنوان",
      "select_type": "حدد النوع",
      "new_req": "طلب جديد",
      "total": "المجموع",
      "ord_samm": "ملخص الطلب",
      "view_states": "عرض الدول",
      "statistics": "إحصائيات",
      "clicks": "النقرات",
      "delivery_charges": "رسوم التوصيل",
      "connected": "متصل",
      "not_connected": "غير متصل",
      "set_price": "تحديد السعر",
      "custom": "مخصص",
      "views": "وجهات النظر",
      "want_holiday_mode": "هل تريد تشغيل وضع العطلة؟",
      "user": "المستخدم",
      "guide_step1_message":
          "اختار اللغة اللي كتريحك وكمّل الرحلة ديالك: الدارجة، الفرنسية ولا الإنجليزية.",
      "guide_step2_message":
          "من شريط التنقل تقدر تشوف الأقسام، تسير البروفايل ديالك وتدخل للإعدادات بسهولة.",
      "guide_step3_message":
          "بغيتي تبيع؟ صوّر، وصف، حطّ الثمن وكليكي على 'بيع منتج'… البيع ولا أسهل!",
      "guide_step4_message":
          "قلب على المنتوج اللي باغي، واستعمل الفيلترات باش توصل ليه بسرعة البرق.",
      "guide_step5_message":
          "عجبك شي منتوج؟ قدم عرضك وتفاوض مباشرة مع البائع… ربّح الوقت والفلوس!",
      "guide_step6_message":
          "كمّل بروفايلك ووثّق رقمك باش تزيد الثقة وتتواصل مع المستخدمين بلا قيود.",
      "guide_step7_message":
          "غادي ترتاح؟ فعّل وضع العطلة باش يبقاو منتوجاتك مخبيين حتى ترجع.",
      "guide_step8_message":
          "جمع أكثر من منتوج من نفس البائع ودير مجموعة باش تنقص مصاريف الشحن.",
      "guide_step9_message":
          "مرحبا بك ف شَدْ مَدْ! بدا دابا البيع، الشراء وتبديل المنتوجات بكل ثقة.",
      "try_now": "جربها دابا",
      "got_it": "واخا!",
      "create_bundle": "دير مجموعة",
      "start_exploring": "يلا نكتاشفو",
      'show_more': 'المزيد',
      'show_less': 'إظهار أقل',
    };
    const Map<String, String> lang_fr = {
      "order_placed": "Commande passée",
      "order_accepted": "Commande acceptée",
      "complete": "complet",
      "order_processed": "Commande traitée",
      "order_ready": "Commande prête à être récupérée",
      "order_completed": "Commande terminée",
      "drafts": "Brouillons",
      "place_ord": "Passer la commande",
      "published": "Publié",
      "protection": "Protection de l'acheteur",
      "protection_include": "Incluant la protection de l'acheteur",
      "sales": "Ventes",
      "incl": "incl.",
      "add_to_cart": "Ajouter au panier",
      "published_items": "Articles publiés",
      "pending_pickup": "En attente de récupération",
      "buying": "Achats",
      "wishlist": "Liste de souhaits",
      "shopping_cart": "Panier d'achat",
      "to_pick": "À récupérer",
      "sure_delete_item":
          "Êtes-vous sûr de vouloir supprimer l'article et ses images ? Cette action est irréversible.",
      "yes": "Oui",
      "no": "Non",
      "are_you_sure": "Êtes-vous sûr ?",
      "ok": "OK",
      "cancel": "Annuler",
      "title": "Titre",
      "description": "Description",
      "color": "Couleur",
      "material": "Matériau",
      "size": "Taille",
      "weight": "Poids",
      "items_hidden": "Vos éléments sont masqués",
      "holday_on": "Les vacances sont maintenant arrivées",
      "condition": "Condition",
      "recommended-price": "Prix recommandé",
      "style": "Style",
      "publish": "Publier",
      "delete": "Supprimer",
      "edit": "Modifier",
      "language": "Langue",
      "developer-settings": "Paramètres développeur",
      "my-addresses": "Mes adress",
      "edit-profile": "Modifier le profil",
      "notifications": "Notifications",
      "new_request": "nouvelle demande",
      "settings": "Paramètres",
      "about-us": "À propos de nous",
      "faqs": "FAQs",
      "contact-us": "Contactez-nous",
      "contact": "Contact",
      "logout": "Se déconnecter",
      "want-to-logout": "Voulez-vous vraiment vous déconnecter ?",
      "add-to-wishlist":
          "Appuyez sur l'icône en forme de cœur sur les articles de la boutique pour les ajouter à votre liste de souhaits.",
      "unpublish": "Dépublier",
      "location_access_details":
          "Pour voir les produits à proximité, fournissez votre code postal ou autorisez votre localisation :",
      "location_access": "Accès à la localisation",
      "location_disable": "Les services de localisation sont désactivés",
      "location_permision_den":
          "Les permissions de localisation sont refusées.",
      "location_permision_den_permanent":
          "Les permissions de localisation sont définitivement refusées, nous ne pouvons pas les demander.",
      "allow": "AUTORISER",
      "do_you_really_want_to_close_the_application":
          "Voulez-vous vraiment fermer l'application ?",
      "buy": "Acheter",
      "sell": "Vendre",
      "sell_an_item": "Vendre un article",
      "product_saved_successfully": "Produit enregistré avec succès !",
      "success": "Succès !!",
      "error": "Erreur !",
      "unexpected_error":
          "Une erreur inattendue est survenue, veuillez réessayer plus tard.",
      "item_price_should_be_added": "Le prix de l'article doit être ajouté !",
      "product_updated_successfully": "Produit mis à jour avec succès !",
      "product_unpublished_successfully": "Produit dépublié avec succès !",
      "product_deleted_successfully": "Produit supprimé avec succès !",
      "pickup": "Ramassage",
      "failed": "Échec du chargement !",
      "verify_email": "vérifiez votre e-mail ou votre numéro de téléphone",
      "complete_profile": "profil non complété",
      "profile_not_com": "Veuillez compléter votre profil",
      "take_picture": "Prendre une photo",
      "do_you_really_want_to_delete_this_image":
          "Voulez-vous vraiment supprimer cette image ?",
      "done": "Terminé",
      "order": "Commande#",
      "status": "Statut : ",
      "track_order": "Suivre la commande",
      "new_address_added": "Nouvelle adresse ajoutée avec succès !",
      "new_address_updated": "Adresse mise à jour avec succès !",
      "add_address": "Ajouter une adresse",
      "selling_address": "Adresse de vente",
      "to_be_able_to_publish":
          "Pour pouvoir publier, vous devez fournir votre adresse",
      "address_line_1": "Adresse ligne 1",
      "required_field": "Champ requis",
      "address_line_2": "Adresse ligne 2",
      "edit_address": "Modifier l'adresse",
      "edit_product": "Modifier le produit",
      "update_product": "Mettre à jour le produit",
      "save_address": "Enregistrer l'adresse",
      "addresses": "Adresses",
      "address_not_found": "Adresse non trouvée",
      "add_new_address": "Ajouter une nouvelle adresse",
      "address": "Adresse",
      "do_you_really_want_to_delete_this_address":
          "Voulez-vous vraiment supprimer cette adresse ?",
      "address_selected_as_default": "Adresse sélectionnée par défaut",
      "welcome_to": "Bienvenue à",
      "please_login_with_your": "Veuillez vous connecter avec votre :",
      "order_is_not_been_accepted": "La commande n'a pas été acceptée",
      "alert": "Alerte !",
      "choose_your_address": "Veuillez entrer votre adresse pour continuer",
      "default_address": "Adresse par défaut : ",
      "pay_now": "Payer maintenant",
      "payment_met": "Mode de paiement",
      "ordered_items": "Articles commandés",
      "seller_details": "Détails du vendeur : ",
      "name": "Nom",
      "phone": "Téléphone",
      "completed": "Terminé",
      "order_completed_on": "Commande terminée le ",
      "you_need_to_mark_complete_after_pickup":
          "Vous devez marquer comme complété après le retrait",
      "payment_will_be_released_to_seller": "Le paiement sera versé au vendeur",
      "mark": "Marquer",
      "enter_card_details":
          "Veuillez entrer les détails de votre carte bancaire",
      "payment_cancelled": "Paiement annulé, veuillez réessayer",
      "select_payment": "Veuillez sélectionner un mode de paiement",
      "payment_unsuccessful": "Paiement échoué, veuillez réessayer",
      "order_placed_successfully": "Votre commande a été passée avec succès",
      "chats": "Chats",
      "search": "Rechercher",
      "write_message": "Écrire un message",
      "price": "Prix",
      "model": "Modèle",
      "and": "et",
      "brand": "Marque",
      "payment": "paiement",
      "you_will_now_see_products_near_you":
          "Vous verrez maintenant des produits près de chez vous",
      "search_products": "Rechercher des produits...",
      "filter_by_categories": "Filtrer par catégories",
      "categories": "Catégories",
      "categories_not_found": "Catégories non trouvées !",
      "clear": "Effacer",
      "sub_categories": "Sous-catégories :",
      "apply": "Appliquer",
      "edit_profile": "Modifier le profil",
      "first_name": "Prénom",
      "last_name": "Nom de famille",
      "phone_no": "Numéro de téléphone",
      "update": "Mettre à jour",
      "enter_valid_email": "Veuillez entrer une adresse e-mail valide",
      "enter_valid_phone": "Veuillez entrer un numéro de téléphone valide",
      "profile_successfully_updated": "Profil mis à jour avec succès",
      "select_language": "Sélectionner la langue",
      "select_locker": "sélectionner un casier",
      "languages": "Langues",
      "automatic": "Automatique",
      "swedish": "Suédois",
      "english": "Anglais",
      "do_you_really_want_to_delete_this_notification":
          "Voulez-vous vraiment supprimer cette notification ?",
      "notification_delete_successfully": "Notification supprimée avec succès",
      "bankid_login": "Connexion BankID",
      "change": "Changer",
      "you_are_logged_out": "Vous êtes déconnecté.",
      "category_required": "Catégorie requise !",
      "please_select_category_and_sub_category_for_the_item":
          "Veuillez sélectionner une catégorie et une sous-catégorie pour l'article",
      "buyer_details": "Détails de l'acheteur",
      "details": "Détails",
      "marked_as_accepted": "Marqué comme accepté",
      "buyer_will_be_notified":
          "L'acheteur sera informé de la préparation de la commande.",
      "buyer_will_pick_the_order":
          "L'acheteur viendra chercher la commande à l'emplacement donné.",
      "you_need_to_mark_for_pickup":
          "Vous devez marquer comme terminé après la collecte",
      "favorites": "Favoris",
      "summary": "résumé",
      "netpay": "Salaire net",
      "saltax": "Taxe de vente",
      "commession": "Commission Plateforme",
      "you_cant_buy_your_product":
          "Vous ne pouvez pas acheter vos propres produits",
      "cart": "Panier",
      "your_searches": "Vos recherches",
      "items": "Articles",
      "members": "Membres",
      "members_item": "Articles des membres",
      "similar_item": "Articles similaires",
      "no_items_added":
          "Aucun autre article ajouté par ce membre pour le moment !",
      "next": "Suivant",
      "reviews": "Avis",
      "reviews_not_added": "Avis non ajouté pour le moment !",
      "start_now": "Commencez maintenant !",
      "onboarding_title1": "Vendez facilement",
      "onboarding_title2": "Achetez en toute confiance",
      "onboarding_title3": "Achetez aujourd'hui, vendez demain",
      "onboarding_title4": "Paiement à la livraison",
      "onboarding_des1":
          "Prenez une photo de l'article que vous souhaitez vendre, ajoutez une description et fixez votre prix. En quelques étapes simples, votre article est prêt à être découvert par des acheteurs potentiels.",
      "onboarding_des2":
          "Parcourez une large gamme de vêtements et accessoires d'occasion. Trouvez des articles uniques et de qualité à des prix abordables.",
      "onboarding_des3":
          "Aujourd'hui, trouvez des trésors pour votre garde-robe. Demain, vendez ce que vous n'utilisez plus et libérez votre dressing. Rejoignez notre communauté et participez à l'économie circulaire de la mode.",
      "onboarding_des4":
          "Achetez et vendez en toute sécurité dans toutes les villes du Maroc",
      "welcom_text":
          "Devenez une partie de la tendance de la seconde main et profitez de la vente gratuite !",
      "login": "Connexion",
      "login_required_description":
          "Il semble que vous ne soyez pas connecté, vous devez d'abord vous connecter...",
      "login_required": "Connexion requise !",
      "signup": "Inscription",
      "continue_guest": "Continuer en tant qu'invité ?",
      "login_trext": "Connectez-vous à votre compte",
      "cor_email_text": "Ou utilisez l'adresse e-mail",
      "email": "E-mail",
      "email_validation": "Veuillez entrer une adresse e-mail valide",
      "password": "Mot de passe",
      "password_dont_match": "Les mots de passe ne correspondent pas",
      "enter_password": "Veuillez entrer votre mot de passe",
      "enter_password_again":
          "Veuillez entrer à nouveau votre nouveau mot de passe",
      "password_include_character":
          "Le mot de passe doit contenir 8 caractères",
      "confirm_password": "Confirmer le mot de passe",
      "forgot_password": "Mot de passe oublié ?",
      "new_member_text": "Nouveau membre ?",
      "already_member": "Déjà membre ?",
      "continue": "Continuer",
      "new_account": "Créer un nouveau compte",
      "account": "Compte",
      "agreement_text": "En vous inscrivant, vous acceptez nos",
      "terms": "Conditions d'utilisation",
      "privacy": "Politique de confidentialité",
      "get_code": "Obtenir le code",
      "verification": "Vérification",
      "send_again": "Envoyer à nouveau",
      "send_offer": "Envoyer une offre",
      "verify": "Vérifier",
      "verified": "vérifié",
      "not_verified": "non vérifié",
      "email_verification": "vérification des e-mails",
      "phone_verification": "Vérification par téléphone",
      "input_field": "Champ de saisie requis",
      "progress": "Encore en cours",
      "otp_sent_success": "OTP envoyé avec succès",
      "new_password": "Nouveau mot de passe",
      "confirm_new_pass": "Confirmer le nouveau mot de passe",
      "update_pass": "Mettre à jour le mot de passe",
      "registration": "Inscription",
      "profile": "Profil",
      "about": "À propos",
      "gender": "Genre",
      "country": "Pays",
      "state": "État",
      "city": "Ville",
      "street": "Rue",
      "bio": "Bio....",
      "submit": "Soumettre",
      "skip": "Passer",
      "undefined_error":
          "Une erreur indéfinie s'est produite, veuillez réessayer plus tard.",
      "add": "AJOUTER",
      "view_all": "Voir tout",
      "guest_user": "Utilisateur invité",
      "good_morning": "Bonjour",
      "good_afternoon": "Bon après-midi",
      "good_evening": "Bonsoir",
      "all_cat": "Toutes les catégories",
      "change_filter":
          "Aucun produit trouvé pour ce filtre, changez vos filtres",
      "category": "catégorie",
      "save": "Enregistrer",
      "home": "Accueil",
      "products": "Produits",
      "filter": "Filtrer",
      "products_not_found": "Produits non trouvés !",
      "make_offer": "Faire une offre",
      "buy_now": "Acheter maintenant",
      "interest": "Intérêts",
      "view_by": "Vu par",
      "uploaded": "Téléchargé",
      "upload": "Télécharger",
      "uploaded_photo": "Télécharger une photo",
      "take_photo": "Prendre une photo",
      "uploaded_photo_text": "Téléchargez jusqu'à 15 photos.",
      "list_by": "Listé par",
      "ask_seller": "Demander au vendeur",
      "natural_light": "Lumière naturelle",
      "year": "Année",
      "ago": "il y a",
      "month": "mois",
      "day": "jour",
      "today": "Aujourd'hui",
      "pruduct_search": "Veuillez rechercher des produits !",
      "close": "Fermer",
      "sort_by": "Trier par",
      "price_rage": "Plage de prix",
      "lo_to_hi": "Du bas vers le haut",
      "hi_to_lo": "Du haut vers le bas",
      "newest_first": "Le plus récent en premier",
      "from": "De",
      "to": "À",
      "see_tips": "Voir les conseils photo",
      "parcel_size": "Taille du colis",
      "photo_tips": "Conseils photo",
      "color_selection": "Vous ne pouvez sélectionner que deux couleurs",
      "chose_natural_light": "Choisissez une lumière naturelle",
      "pick_neutral_background": "Choisissez un fond neutre",
      "dont_flash": "N'utilisez pas le flash",
      "show_items": "Montrez vos articles",
      "own_images": "Utilisez vos propres images",
      "product_uploaded": "Produit téléchargé !",
      "product_upload_message":
          "Produit ajouté avec succès, veuillez attendre l'approbation",
      "my_profile": "Mon profil",
      "my_ads": "Frais Spotlight :",
      "spotlight_charges": "Mes annonces",
      "bump_item": "Boostez vos articles",
      "store_spotlight": "Mettez en valeur votre magasin",
      "boos_visib": "Boostez votre visibilité",
      "my_listing": "Mes listes",
      "my_order": "Mes commandes",
      "my_wallet": "Mon portefeuille",
      "my_address": "Mes adresses",
      "fav_items": "Articles favoris",
      "hide_items": "Cacher mes objets",
      "personalisation": "Personnalisation",
      "account_settings": "Paramètres du compte",
      "other_setting": "Autres paramètres",
      "others": "autres",
      "impressions": "impressions",
      "no_products": "Aucun produit listé pour le moment",
      "sold": "vContinuer",
      "bought": "Acheté",
      "no_pen_orders": "Aucune commande en attente",
      "no_proc_order": "Aucune commande en cours de traitement",
      "no_com_order": "Aucune commande terminée",
      "no_can_order": "Aucune commande annulée",
      "no_ord_placed": "Aucune commande passée pour le moment",
      "all": "Tous",
      "pending": "En attente",
      "processing": "En cours de traitement",
      "offer_message":
          "Votre offre doit être au moins 40 % inférieure au prix initial",
      "cancelled": "Annulé",
      "history": "Historique",
      "no_trans": "Vous n'avez aucune transaction",
      "balance": "Solde disponible",
      "withdraw": "Retirer",
      "bank_account_seleted": "Le compte bancaire doit être sélectionné",
      "withdraw_text":
          "Il peut falloir jusqu'à 5 jours ouvrables pour que les fonds atteignent votre compte bancaire.",
      "upcomming_bal": "Solde à venir",
      "no_fav": "Aucun produit dans la liste de souhaits",
      "personalize_feed":
          "Choisissez vos catégories et tailles préférées pour personnaliser votre flux",
      "following": "Suivi",
      "aply_person": "Personnalisation appliquée avec succès",
      "account_sett": "Paramètres du compte",
      "not_sel": "Non sélectionné",
      "not_spec": "Non spécifié",
      "on": "Activé",
      "off": "Désactivé",
      "holy_day": "Mode vacances",
      "dob": "Date de naissance",
      "enter_dob": "Entrez la date de naissance",
      "acc_sync": "Comptes et synchronisation",
      "email_phone_ver": "Vérification de l'e-mail et du téléphone",
      "delete_acc": "Supprimer le compte",
      "delete_account_text": "Voulez-vous vraiment supprimer votre compte ?",
      "chagne_pass": "Changer le mot de passe",
      "chagne_pass_text": "Mot de passe changé avec succès",
      "current_pass": "Mot de passe actuel",
      "enter_current_pass": "Veuillez entrer votre mot de passe actuel",
      "dark_mode": "Mode sombre",
      "bundle_discount": "Remise groupée",
      "enable_bundel_dis": "Activer la remise groupée",
      "setup_dis": "Configurer la remise",
      "bundle_discount_success": "Remise groupée créée avec succès",
      "two_factor": "Authentification à deux facteurs (2FA)",
      "terms_and_con": "Conditions générales",
      "return_policy": "Politique de retour et de remboursement",
      "customer_support": "Service client",
      "no_support_req": "Aucune demande d'assistance trouvée!",
      "invalid_pass": "Mot de passe invalide",
      "disconut_selection_text":
          "Le pourcentage de remise doit être sélectionné",
      "user_blocked": "Cet utilisateur a été bloqué",
      "user_reported": "L'utilisateur a été signalé",
      "report_user_text": "Êtes-vous sûr de vouloir signaler ce compte ?",
      "report": "Signaler",
      "report_user": "Signaler l'utilisateur",
      "or": "Ou",
      "delivery_address": "Adresse de livraison",
      "delivery_company": "Sociétés de livraison",
      "shipping_service_not_av": "Service de livraison non disponible",
      "shipping_service_selected":
          "Le service de livraison doit être sélectionné",
      "save_filter": "Filtre enregistré avec succès",
      "withdraw_request_succes":
          "Votre demande de retrait a été envoyée avec succès",
      "withdraw_request": "Demande de retrait",
      "amount": "Montant",
      "no_bank_account": "Aucun compte bancaire ajouté pour le moment",
      "add_new": "Ajouter un nouveau compte",
      "review_success": "Avis ajouté avec succès",
      "location_entered": "L'emplacement doit être saisi",
      "conversation_blocked": "Vous avez bloqué cette conversation",
      "user_blocked_you": "Vous avez été bloqué par cet utilisateur",
      "accept": "Accepter",
      "reject": "Rejeter",
      "help_center": "Centre d'aide",
      "checkout": "Commander",
      "withDraw": "Retirer",
      "say_somthing": "Dire quelque chose",
      "rating": "Notation",
      "no_comment": "Sans commentaires",
      "proceed": "Procéder",
      "proceed_checkout": "Passer à la caisse",
      "review": "Revoir",
      "gallery": "Galerie",
      "pick_image": "Choisir une image",
      "member_since": "Membre depuis",
      "block": "Bloquer",
      "block_user_text": "Êtes-vous sûr de vouloir bloquer cet utilisateur ?",
      "block_user": "Bloquer l'utilisateur",
      "delete_convesation": "Supprimer la conversation",
      "delete_conversation_text":
          "Êtes-vous sûr de vouloir supprimer cette conversation ?",
      "delete_chat": "Supprimer le chat",
      "order_detail": "détail de la commande",
      "order_id": "Numéro de commande",
      "last_update": "Dernière mise à jour :",
      "shipping_addr": "Adresse de livraison:",
      "subtotal": "Sous total",
      "minuts": "minutes",
      "finances": "FINANCES",
      "order_supp": "COMMANDE",
      "prod_supp": "PRODUIT",
      "withdraw_supp": "RETIRER",
      "deposite": "DÉPÔT",
      "enter_message": "Veuillez entrer un message",
      "enter_title": "Veuillez entrer un titre",
      "select_type": "Sélectionnez le type",
      "new_req": "Nouvelle demande",
      "total": "total",
      "ord_samm": "Récapitulatif de la commande:",
      "view_states": "Afficher les états",
      "statistics": "statistiques",
      "clicks": "Clics",
      "delivery_charges": "Frais de livraison",
      "connected": "Connecté",
      "not_connected": "non connecté",
      "set_price": "fixer un prix",
      "custom": "coutume",
      "views": "vues",
      "want_holiday_mode": "Voulez-vous activer le mode vacances ?",
      "user": "Utilisateur",
      "guide_step1_message":
          "Choisissez votre langue préférée pour continuer : Français, Anglais ou Darija.",
      "guide_step2_message":
          "Utilisez la barre de navigation pour explorer les catégories, gérer votre profil et accéder aux paramètres.",
      "guide_step3_message":
          "Cliquez sur 'Vendre un produit' pour publier vos articles. Ajoutez des photos, une description et fixez votre prix !",
      "guide_step4_message":
          "Utilisez la barre de recherche pour trouver des articles qui vous intéressent. Appliquez des filtres pour affiner votre recherche.",
      "guide_step5_message":
          "Vous avez trouvé un article qui vous plaît ? Proposez un prix et négociez directement avec le vendeur !",
      "guide_step6_message":
          "Accédez à votre profil pour le modifier et confirmer votre numéro de téléphone. Cela renforce la confiance avec les autres utilisateurs.",
      "guide_step7_message":
          "Vous partez en vacances ? Activez le mode vacances dans les paramètres pour cacher temporairement vos articles.",
      "guide_step8_message":
          "Regroupez plusieurs articles d’un même vendeur pour créer un lot et économiser sur les frais de livraison. Cliquez sur 'Créer un lot' pour commencer !",
      "guide_step9_message":
          "Vous êtes prêt à explorer شَدْ مَدْ ! Commencez à acheter, vendre et échanger vos articles dès aujourd’hui.",
      "try_now": "Essayer maintenant",
      "got_it": "Compris !",
      "create_bundle": "Créer un lot",
      "start_exploring": "Commencer à explorer",
      'show_more': 'Afficher plus',
      'show_less': 'Afficher moins',
    };

    return {
      'en': lang_en,
      'ar': lang_ar,
      'fr': lang_fr,
    };
  }
}
